# Generated by Django 3.2.12 on 2022-03-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
