# Generated by Django 3.2.12 on 2022-03-31 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_job_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='deadline',
        ),
    ]
